export const STREET_NUMBER = "15041 Calvert St.";
export const CITY = "Van Nuys";
export const STATE = "CA";
export const ZIP = "91411";
export const STREET_ADDRESS = `${STREET_NUMBER}, ${CITY}, ${STATE} ${ZIP}`;

// Domains that are allowed to display the video section
export const VIDEO_DOMAIN_WHITELIST = [
	"splitsystemnear.com",
	"splitsystemsnear.com",
	"localhost",
	"127.0.0.1",
];

// Adjacent location words for title formatting
export const ADJACENT_LOCATION_WORDS = [
	"near",
	"in",
	"around",
	"close to",
	"nearby",
	"within",
	"surrounding",
	"adjacent to",
	"next to",
	"by",
	"at",
	"in the vicinity of",
];

// Default domain to use as fallback
export const DEFAULT_DOMAIN = "airconditioner.com";
export const DEFAULT_TITLE = "Air Conditioner";
// Localhost patterns that should be replaced with the default domain
export const LOCALHOST_PATTERNS = ["localhost", "127.0.0.1"];

// Special terms that should maintain specific formatting
export const SPECIAL_TERMS = {
	ptac: "PTAC",
	hvac: "HVAC",
	ac: "AC",
	rv: "RV",
	minisplit: "Mini Split",
	minisplits: "Mini Splits",
	splitsystem: "Split System",
	splitsystems: "Split Systems",
	heatpump: "Heat Pump",
	heatpumps: "Heat Pumps",
	airconditioner: "Air Conditioner",
	airconditioners: "Air Conditioners",
	airconditioning: "Air Conditioning",
	airconditionerunit: "Air Conditioner Unit",
	airconditionerunits: "Air Conditioner Units",
};

// Small words that should remain lowercase in titles (unless first or last word)
export const SMALL_WORDS = [
	"a",
	"an",
	"and",
	"as",
	"at",
	"but",
	"by",
	"en",
	"for",
	"if",
	"in",
	"nor",
	"of",
	"on",
	"or",
	"per",
	"the",
	"to",
	"vs",
	"via",
];

// Words that should always be uppercase
export const ALWAYS_UPPERCASE = ["HVAC", "AC", "PTAC", "RV"];

export const CITIES = [
	"Anaheim",
	"Antioch",
	"Bakersfield",
	"Berkeley",
	"Burbank",
	"Carlsbad",
	"Chico",
	"Chula Vista",
	"Clovis",
	"Compton",
	"Concord",
	"Corona",
	"Costa Mesa",
	"Daly City",
	"Downey",
	"El Cajon",
	"El Monte",
	"Elk Grove",
	"Escondido",
	"Fairfield",
	"Fontana",
	"Folsom",
	"Fremont",
	"Fresno",
	"Fullerton",
	"Garden Grove",
	"Glendale",
	"Hayward",
	"Hemet",
	"Hesperia",
	"Huntington Beach",
	"Indio",
	"Inglewood",
	"Irvine",
	"Jurupa Valley",
	"Lake Forest",
	"Lancaster",
	"Livermore",
	"Long Beach",
	"Los Angeles",
	"Menifee",
	"Merced",
	"Milpitas",
	"Mission Viejo",
	"Modesto",
	"Moreno Valley",
	"Murrieta",
	"Napa",
	"Norwalk",
	"Oakland",
	"Oceanside",
	"Ontario",
	"Orange",
	"Oxnard",
	"Palmdale",
	"Pasadena",
	"Pomona",
	"Rancho Cucamonga",
	"Redding",
	"Redwood City",
	"Richmond",
	"Riverside",
	"Roseville",
	"Sacramento",
	"Salinas",
	"San Bernardino",
	"San Diego",
	"San Francisco",
	"San Jose",
	"San Leandro",
	"San Marcos",
	"San Mateo",
	"San Ramon",
	"Santa Ana",
	"Santa Barbara",
	"Santa Clara",
	"Santa Clarita",
	"Santa Maria",
	"Santa Monica",
	"Santa Rosa",
	"Simi Valley",
	"South Gate",
	"Stockton",
	"Sunnyvale",
	"Temecula",
	"Thousand Oaks",
	"Torrance",
	"Tracy",
	"Tustin",
	"Vacaville",
	"Vallejo",
	"Ventura",
	"Victorville",
	"Visalia",
	"Vista",
	"Walnut Creek",
	"West Covina",
	"Westminster",
	"Whittier",
];

export const SLUGS = [
	"AC",
	"AC Unit",
	"Air Conditioner",
	"Mini Split",
	"Heat Pump",
	"Split System",
];

export const PRODUCTS = [
	"Motel PTACs",
	"Hotel PTACs",
	"Packaged Terminal Air Conditioners",
	"Packaged Air Conditioners",
	"Packaged Heat Pump",
	"Packaged Air Conditioning",
	"Packaged Gas Electric Air Conditioning",
	"Heaters",
	"Furnaces",
	"Air Conditioners",
	"Air Conditioning",
	"AC Units",
	"Air Conditioner Units",
	"HVAC Mini Splits",
	"Mini Splits",
	"Heat Pump Mini Splits",
	"Mini Split Heat Pumps",
	"Heat Pumps",
	"Swamp Coolers",
	"Dehumidifiers",
	"Systems",
	"High Efficiency",
	"Reconditioned",
	"Energy Saving",
	"Through Wall",
	"Through the Wall",
	"Wall Mounted",
	"Low Profile",
	"Commercial",
	"Residential",
	"Wall Mount",
	"Wall",
	"Apartment",
	"Efficient",
	"Multizone",
	"Multiroom",
	"Room",
	"Dual Zone",
	"Multi Zone",
	"Single Zone",
	"Ductless",
	"Electric",
	"Builders",
	"Infrared",
	"Ventless",
	"Window",
	"Slide Out",
	"Slimline",
	"Thruwall",
	"Vertical",
	"Portable",
	"Outdoor",
	"Indoor",
	"Bedroom",
	"Central",
	"Radiant",
	"Rooftop",
	"Vented",
	"Ducted",
	"Ductless",
	"Remanufactured",
	"Comfort Star",
	"Genie Aire",
	"Cooper and Hunter",
	"CH",
	"Genie",
];

export const ACCESSORIES = [
	"Remote Controls",
	"Transformers",
	"Refrigerants",
	"Thermostats",
	"Compressors",
	"Accessories",
	"Condensers",
	"Capacitors",
	"Appliances",
	"Inverters",
	"Supplies",
	"Brackets",
	"Switches",
	"Cassettes",
	"Filters",
	"Sleeves",
	"Linesets",
	"Remotes",
	"Tools",
	"Coils",
	"Freon",
	"Knobs",
	"Heat Strips",
];

export const BUSINESSES = [
	"Manufacturers",
	"Distributors",
	"Wholesalers",
	"Liquidators",
	"Warranties",
	"Equipment",
	"Closeouts",
	"Discounts",
	"Financing",
	"Suppliers",
	"Warehouse",
	"Specials",
	"Products",
	"Supplies",
	"Dealers",
	"Ratings",
	"Rebates",
	"Surplus",
	"Parts",
	"Sales",
	"Repair",
	"Service",
	"Installation",
	"For Homes",
	"For Hotels",
	"For Apartments",
];

export const DUCTED_KEYWORDS = [
	"a/c",
	"ac cooling system",
	"air conditioning systems",
	"split systems",
	"heat and cool",
	"cheap mini splits",
	"cooling units",
	"central air heat pump",
	"air split",
	"air conditioning cleaning",
	"mini split air conditioners",
	"mini split installation",
	"air to water heat pump",
	"split cooling system",
	"hvac units",
	"hvac unit",
	"hvac air conditioning",
	"ductless air conditioner installation",
	"multi split",
	"what is a mini split",
	"heating and ac",
	"best mini split heat pump",
	"what is a mini split heat pump",
	"multi zone mini split",
	"air heat",
	"mini split",
	"hvac repair",
	"split heat",
	"mobile air conditioner",
	"air unit",
	"hvac companies near me",
	"ac heating and air",
	"air conditioner unit",
	"home aircon",
	"air conditioner heater",
	"split aircon",
	"high efficiency ac unit",
	"new air conditioner",
	"split air unit",
	"split type aircon",
	"mini split ac",
	"aircon unit",
	"air conditioner split",
	"heat pump ac unit",
	"air conditioner tune up near me",
	"heating and cooling near me",
	"air conditioner window",
	"heating and air conditioning services",
	"cheap split system air conditioners sale",
	"hyper heat mini split",
	"cooling air conditioner",
	"heating and cooling",
	"mini split not heating",
	"air conditioner installation near me",
	"18000 btu mini split",
	"hvac replacement near me",
	"mini split multi zone",
	"mini split air conditioner",
	"quality air",
	"room air conditioner",
	"aircon mini split",
	"mini split heat pump installation",
	"mini split ac and heat",
	"ductless heating",
	"mini split with heat",
	"mini split inverter",
	"heating air conditioning",
	"split system air conditioner",
	"split air conditioning",
	"24 hour hvac near me",
	"air conditioning repair",
	"air conditioning service",
	"split unit aircon",
	"heating unit",
	"aircon",
	"mini split air",
	"ac mini split",
	"heat pump heating system",
	"small split system air conditioner",
	"conditioned air",
	"air conditioner company",
	"wall mounted air conditioner",
	"commercial hvac",
	"ductless heat pump",
	"air heat pump",
	"fix air conditioner",
	"home heating and cooling",
	"what is a split system heat pump",
	"hvac tune up cost",
	"air conditioning unit",
	"heat pump air conditioner",
	"ac heat pump",
	"air conditioner installation",
	"heat pump",
	"heat pump hvac",
	"hvac service",
	"air conditioning company",
	"electric heat pump",
	"air conditioning installation",
	"ac prices",
	"air conditioner heat pump",
	"air conditioner companies",
	"multi split aircon",
	"air conditioner canada",
	"indoor air conditioner",
	"furnace and air conditioner",
	"cooling and heating",
	"air unit for house",
	"24000 btu mini split",
	"12000 btu mini split",
	"ac and heating repair",
	"heating air conditioning near me",
	"air conditioning",
	"mini split systems",
	"heater and air conditioner",
	"heat and air conditioning",
	"split air conditioner",
	"genie mini split",
	"air cooling unit",
	"air conditioner",
	"hvac technician",
	"heat and air near me",
	"one hour air",
	"split unit",
	"air conditioner price",
	"aircon price",
	"dual zone mini split",
	"mini air conditioner",
	"hvac system",
	"small ac unit for room",
	"ductless mini split",
	"air conditioning maintenance",
	"heat and air",
	"multi split system",
	"mini split heat pump",
	"energy efficient air conditioner",
	"ac heating and cooling",
	"efficiency heating and cooling",
	"air source heat pump",
	"heating cooling",
	"ac installation cost",
	"hvac contractor",
	"mini split ac heat pump",
	"split system heat pump",
];

export const SPLIT_KEYWORDS = [
	"Installation",
	"Repair",
	"Maintenance",
	"Systems",
	"Air Conditioning",
	"Heat Pump",
	"Indoor Units",
	"Outdoor Units",
	"Efficiency",
	"Cooling Solution",
	"Heating Solution",
	"Zoning",
	"Energy Savings",
	"Multi Zone",
	"Single Zone",
	"Mini Split",
	"Wall Mount",
	"Ceiling Cassette",
	"Floor Mount",
	"Concealed Duct",
];

export const HVAC_KEYWORDS = [
	"Installation",
	"Repair",
	"Maintenance",
	"Service",
	"Technician",
	"Certification",
	"Commercial",
	"Residential",
	"Air Quality",
	"Ventilation",
	"Heating",
	"Cooling",
	"Refrigeration",
	"Ductwork",
	"Energy Efficiency",
	"Seasonal Maintenance",
	"Filter Replacement",
	"Thermostat",
	"System Upgrade",
	"Temperature Control",
];

export const createDomainTitleMap = () => {
	const map = new Map();

	// Add mappings with regex patterns
	map.set(/^acminisplits?near\.com$/, "AC Mini Split Near");
	map.set(/^acsplitservices?\.com$/, "AC Split Services");
	map.set(/^splitsystems?near\.com$/, "Split System Near");
	map.set(/^heatpumps?installations?\.com$/, "Heat Pump Installation");
	map.set(/^acsplitsystems?\.com$/, "AC Split System");
	map.set(/^(mini)?splits?systems?\.com$/, "Split System");
	map.set(/^heatpumps?(mini)?splits?\.com$/, "Heat Pump Mini Split");

	// Add more mappings as needed

	return map;
};

// Keep your original mappings for exact matches
export const DOMAIN_TITLE_MAPPINGS = {
	"acsplitservices.com": "AC Split Services",
	"splitsystemnear.com": "Split System Near",
	"heatpumpinstallation.com": "Heat Pump Installation",
	// Add more domain-to-title mappings as needed
};
