export const STREET_NUMBER = "15041 Calvert St.";
export const CITY = "Van Nuys";
export const STATE = "CA";
export const ZIP = "91411";
export const STREET_ADDRESS = `${STREET_NUMBER}, ${CITY}, ${STATE} ${ZIP}`;

export const ADJACENT_LOCATION_WORDS = [
	"near",
	"in",
	"around",
	"close to",
	"nearby",
	"within",
	"surrounding",
	"adjacent to",
	"next to",
	"by",
	"at",
	"in the vicinity of",
];

export const CITIES = [
	"Anaheim",
	"Antioch",
	"Bakersfield",
	"Berkeley",
	"Burbank",
	"Carlsbad",
	"Chico",
	"Chula Vista",
	"Clovis",
	"Compton",
	"Concord",
	"Corona",
	"Costa Mesa",
	"Daly City",
	"Downey",
	"El Cajon",
	"El Monte",
	"Elk Grove",
	"Escondido",
	"Fairfield",
	"Fontana",
	"Folsom",
	"Fremont",
	"Fresno",
	"Fullerton",
	"Garden Grove",
	"Glendale",
	"Hayward",
	"Hemet",
	"Hesperia",
	"Huntington Beach",
	"Indio",
	"Inglewood",
	"Irvine",
	"Jurupa Valley",
	"Lake Forest",
	"Lancaster",
	"Livermore",
	"Long Beach",
	"Los Angeles",
	"Menifee",
	"Merced",
	"Milpitas",
	"Mission Viejo",
	"Modesto",
	"Moreno Valley",
	"Murrieta",
	"Napa",
	"Norwalk",
	"Oakland",
	"Oceanside",
	"Ontario",
	"Orange",
	"Oxnard",
	"Palmdale",
	"Pasadena",
	"Pomona",
	"Rancho Cucamonga",
	"Redding",
	"Redwood City",
	"Richmond",
	"Riverside",
	"Roseville",
	"Sacramento",
	"Salinas",
	"San Bernardino",
	"San Diego",
	"San Francisco",
	"San Jose",
	"San Leandro",
	"San Marcos",
	"San Mateo",
	"San Ramon",
	"Santa Ana",
	"Santa Barbara",
	"Santa Clara",
	"Santa Clarita",
	"Santa Maria",
	"Santa Monica",
	"Santa Rosa",
	"Simi Valley",
	"South Gate",
	"Stockton",
	"Sunnyvale",
	"Temecula",
	"Thousand Oaks",
	"Torrance",
	"Tracy",
	"Tustin",
	"Vacaville",
	"Vallejo",
	"Ventura",
	"Victorville",
	"Visalia",
	"Vista",
	"Walnut Creek",
	"West Covina",
	"Westminster",
	"Whittier",
];

export const SLUGS = [
	"AC",
	"AC Unit",
	"Air Conditioner",
	"Mini Split",
	"Heat Pump",
];

export const PRODUCTS = [
	"Motel PTACs",
	"Hotel PTACs",
	"Packaged Terminal Air Conditioners",
	"Packaged Air Conditioners",
	"Packaged Heat Pump",
	"Packaged Air Conditioning",
	"Packaged Gas Electric Air Conditioning",
	"Heaters",
	"Furnaces",
	"Air Conditioners",
	"Air Conditioning",
	"AC Units",
	"Air Conditioner Units",
	"HVAC Mini Splits",
	"Mini Splits",
	"Heat Pump Mini Splits",
	"Mini Split Heat Pumps",
	"Heat Pumps",
	"Swamp Coolers",
	"Dehumidifiers",
	"Systems",
	"High Efficiency",
	"Reconditioned",
	"Energy Saving",
	"Through Wall",
	"Through the Wall",
	"Wall Mounted",
	"Low Profile",
	"Commercial",
	"Residential",
	"Wall Mount",
	"Wall",
	"Apartment",
	"Efficient",
	"Multizone",
	"Multiroom",
	"Room",
	"Dual Zone",
	"Multi Zone",
	"Single Zone",
	"Ductless",
	"Electric",
	"Builders",
	"Infrared",
	"Ventless",
	"Window",
	"Slide Out",
	"Slimline",
	"Thruwall",
	"Vertical",
	"Portable",
	"Outdoor",
	"Indoor",
	"Bedroom",
	"Central",
	"Radiant",
	"Rooftop",
	"Vented",
	"Ducted",
	"Ductless",
	"Remanufactured",
	"Comfort Star",
	"Genie Aire",
	"Cooper and Hunter",
	"CH",
	"Genie",
];

export const ACCESSORIES = [
	"Remote Controls",
	"Transformers",
	"Refrigerants",
	"Thermostats",
	"Compressors",
	"Accessories",
	"Condensers",
	"Capacitors",
	"Appliances",
	"Inverters",
	"Supplies",
	"Brackets",
	"Switches",
	"Cassettes",
	"Filters",
	"Sleeves",
	"Linesets",
	"Remotes",
	"Tools",
	"Coils",
	"Freon",
	"Knobs",
	"Heat Strips",
];

export const BUSINESSES = [
	"Manufacturers",
	"Distributors",
	"Wholesalers",
	"Liquidators",
	"Warranties",
	"Equipment",
	"Closeouts",
	"Discounts",
	"Financing",
	"Suppliers",
	"Warehouse",
	"Specials",
	"Products",
	"Supplies",
	"Dealers",
	"Ratings",
	"Rebates",
	"Surplus",
	"Parts",
	"Sales",
	"Repair",
	"Service",
	"Installation",
	"For Homes",
	"For Hotels",
	"For Apartments",
];

